name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'pnpm'        
    - name: Install dependencies
      run: pnpm ci

  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check types
      run: pnpm run typecheck
      
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Lint
      run: pnpm run lint
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Test
      run: pnpm run test
